exports.queryList = {
    // Store queries
    GET_STORE_LIST_QUERY : 'SELECT STOREID, STORENAME, STOREADDRESS, STORECODE FROM BOOK.STORE',
    SAVE_STORE_QUERY : 'INSERT INTO BOOK.STORE (STORENAME, STOREADDRESS, STORECODE) VALUES ($1, $2, $3)',
    // Book queries 
    GET_BOOK_LIST_QUERY : 'SELECT BOOKID, BOOKTITLE, BOOKDESC, PUBLISHER, AUTHOR, PAGES FROM BOOK.BOOK',
    GET_BOOK_DETAILS :'SELECT BOOKID, BOOKTITLE, BOOKDESC, PUBLISHER, AUTHOR, PAGES, STORECODE FROM BOOK.BOOK INNER JOIN BOOK.STORE ON BOOK.STORECODE = STORE.STORECODE WHERE BOOKID =$1',
    SAVE_BOOK_QUERY : 'INSERT INTO BOOK.BOOK (BOOKTITLE, BOOKDESC, PUBLISHER, AUTHOR, PAGES) VALUES($1,$2,$3,$4,$5)'
}